# Site settings
name: 太白野老
email: 1251924149@qq.com
author: wangxch
url: http://www.hifreud.com
resume_site: https://www.qhftdx.cn/
github: https://github.com/bpwangxch/
baseurl: "/blog"
description: Stay hungry, stay foolish!
meta_description: wangxch;GIS数据共享;GIS;RS;GPS;地理信息系统;太白野老;个人博客;
motto: Stay hungry, stay foolish!
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bpwangxch

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9


theme: jekyll-theme-cayman